[project]
name = "video-summarization"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Karn Wong", email = "karn@karnwong.me" }
]
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "loguru>=0.7.3",
    "pydub>=0.25.1",
    "tqdm>=4.67.3",
]

[tool.uv]
package = false
